config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  devise_for :advisors, controllers: { omniauth_callbacks: 'advisors/omniauth_callbacks' }, skip: [:sessions]
  as :advisor do
    get 'signin', to: 'devise/sessions#new', as: :new_advisor_session
    post 'signin', to: 'devise/sessions#create', as: :advisor_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_advisor_session
  end
  # authenticated :advisor do
  #   root to: ''
  # end
  resources :courses
  resources :advisors
  resources :students do
    resources :academic_plans
  end

  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :matriculation_term, class_name: 'AcademicTerm'
  belongs_to :graduation_term, class_name: 'AcademicTerm'
  belongs_to :advisor
  belongs_to :major
  has_many :academic_plans, dependent: :destroy
  has_many :courses, through: :academic_plans
  has_many :student_rosters
  has_many :advisors, through: :student_rosters

  accepts_nested_attributes_for :matriculation_term
  accepts_nested_attributes_for :graduation_term

  def graduation_term_attributes=(grad_hash)
    if grad_hash['academic_term_code'].present?
      grad_hash.values.each do |grad|
        grad_term = AcademicTerm.find_or_create_by(academic_term_code: grad)
        self.graduation_term = grad_term
      end
    end
  end

  def matriculation_term_attributes=(grad_hash)
    if grad_hash['academic_term_code'].present?
      grad_hash.values.each do |grad|
        matric_term = AcademicTerm.find_or_create_by(academic_term_code: grad)
        self.matriculation_term = matric_term
      end
    end
  end

  def major_in
    student_major = self.major
    student_major.major_title
  end

  def start_term
    term_start = self.matriculation_term
    term_start.academic_term
  end

  def grad_term
    term_grad = self.graduation_term
    term_grad.academic_term
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

# Student controller class
class StudentsController < ApplicationController

  
  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show; end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  # Only allow a list of trusted parameters through.

  def student_params
    params.require(:student).permit(:preferred_name, :last_name, :major_id, :advisor_id, :ugamyid,
                                    matriculation_term_attributes: %i[academic_term academic_term_code],
                                    graduation_term_attributes: %i[academic_term academic_term_code])
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: @student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ugamyid, 'UGA MyID' %>
    <%= form.text_field :ugamyid %>
  </div>

  <div class="field">
    <%= form.label :preferred_name %>
    <%= form.text_field :preferred_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :major_id, "Select Student's Major" %>
    <%= form.collection_select :major_id, Major.all, :id, :major_code %>
  </div>

  <div class="field">
    <%= form.fields_for :matriculation_term, @student.build_matriculation_term do |matriculation| %>
      <%= matriculation.label :academic_term_code, 'Matriculation Term' %>
      <%= matriculation.text_field :academic_term_code, list: "academic_term_code_autocomplete"%>
        <datalist id="academic_term_code_autocomplete">
          <% AcademicTerm.all.each do |term| %>
            <option value="<%= term.academic_term_code %>"><%= term.academic_term %></option>
          <% end %>
        </datalist>
      <% end %>
  </div>

  <div class="field">
    <%= form.fields_for :graduation_term, @student.build_graduation_term do |graduation| %>
      <%= graduation.label :academic_term_code, 'Graduation Term' %>
      <%= graduation.text_field :academic_term_code, list: "graduation_term_code_autocomplete"%>
      <datalist id="graduation_term_code_autocomplete">
        <% AcademicTerm.all.each do |term| %>
          <option value="<%= term.academic_term_code %>"><%= term.academic_term %></option>
        <% end %>
      </datalist>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :advisor_id, "Select Student's Advisor" %>
    <%= form.collection_select :advisor_id, Advisor.all, :id, :first_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Preferred name</th>
      <th>Last name</th>
      <th>Major</th>
      <th>Advisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisor.students.each do |student| %>
      <tr>
        <td><%= student.preferred_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.major_id %></td>
        <td><%= student.advisor_id %></td>
        <td><%= button_to 'Show', { action: "show", id: "#{student.id}" }, method: :get %></td>
        <td><%= button_to 'Edit', edit_student_path(student), method: :get %></td>
        <td><%= button_to 'Destroy', { action: "destroy", id:"#{student.id}" }, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= console %>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>UGA MyID:</strong>
  <%= @student.ugamyid %>
</p>

<p>
  <strong>Preferred name:</strong>
  <%= @student.preferred_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Major:</strong>
  <%= @student.major_in %>
</p>

<p>
  <strong>Matriculation Term:</strong>
  <%= @student.start_term %>
</p>

<p>
  <strong>Graduation Term:</strong>
  <%= @student.grad_term %>
</p>

<p>
  <strong>Advisor:</strong>
  <%= @student.advisor.first_name %>
</p>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Academic Plan</th>-->
<!--      <th>Advised Term</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
    <%# @student.academic_plans.each do |plan| %>
<!--      <tr>-->
<!--        <td><%#= link_to plan.academic_plan_note, student_academic_plan_path(@student, plan) %></td>-->
<!--        <td><%#= plan.advised_term.academic_term %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %> |
<%= link_to 'View Academic Plans', student_academic_plans_path(@student) %> |
<%= link_to 'New Academic Plan', new_student_academic_plan_path(@student) %>