config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  devise_for :advisors, controllers: { omniauth_callbacks: 'advisors/omniauth_callbacks' }, skip: [:sessions]
  as :advisor do
    get 'signin', to: 'devise/sessions#new', as: :new_advisor_session
    post 'signin', to: 'devise/sessions#create', as: :advisor_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_advisor_session
  end
  # authenticated :advisor do
  #   root to: ''
  # end
  resources :courses
  resources :advisors
  resources :students do
    resources :academic_plans
  end

  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advisor.rb
class Advisor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :ugamyid, uniqueness: true
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]
  # has_secure_password

  # belongs_to :college
  has_many :student_rosters
  has_many :students, through: :student_rosters

  # accepts_nested_attributes_for :college

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def self.from_omniauth(auth)
    @advisor = Advisor.find_by(email: auth.info.email)
    if @advisor
      @advisor.provider = auth.provider
      @advisor.uid = auth.uid
      @advisor.save
    else
      @advisor = Advisor.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

  def college_attributes=(college_hash)
    if college_hash["college_code"].present?
      college_hash.values.each do |college_value|
        college = College.find_or_create_by(college_code: college_value)
        self.college = college
      end
    end
  end
end

app/controllers/advisors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Advisors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  # skip_after_action :verify_authenticity_token, only: :google_oauth2

  def google_oauth2
    @advisor = Advisor.from_omniauth(request.env['omniauth.auth'])

    if @advisor.persisted?
      sign_in_and_redirect @advisor, event: :authenticate
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except!(:extra)
      redirect_to new_advisor_registration_url, alert: @advisor.errors.full_messages.join('\n')
    end
  end

  def failure
    redirect_to root_path
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController

  # GET /advisors or /advisors.json
  def index
    @advisors = Advisor.all
  end

  # GET /advisors/1 or /advisors/1.json
  def show; end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
  end

  # GET /advisors/1/edit
  def edit; end

  # POST /advisors or /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: "Advisor was successfully created." }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1 or /advisors/1.json
  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html { redirect_to @advisor, notice: "Advisor was successfully updated." }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1 or /advisors/1.json
  def destroy
    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to advisors_url, notice: "Advisor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@google.com\z/
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Only allow a list of trusted parameters through.
  def advisor_params
    params.require(:advisor).permit(:first_name, :last_name, :college_id,
                                    :ugamyid, :password,
                                    :password_confirmation,
                                    college_attributes: [:college_code])
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_form.html.erb
<%= form_with(model: advisor) do |form| %>
  <% if advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
        <% advisor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ugamyid, 'UGA MyID' %>
    <%= form.text_field :ugamyid %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.fields_for :college, @advisor.build_college do |college_field| %>
      <div class="field">
        <%= college_field.label :college_code, "College Code" %>
        <%= college_field.text_field :college_code %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advisors/edit.html.erb
<h1>Editing Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advisors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisors.each do |advisor| %>
      <tr>
        <td><%= advisor.first_name %></td>
        <td><%= advisor.last_name %></td>
        <td><%= advisor.college_id %></td>
        <td><%= link_to 'Show', advisor %></td>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<h1>New Advisor</h1>

<%= render 'form', advisor: @advisor %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @advisor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @advisor.last_name %>
</p>

<p>
  <strong>College:</strong>
  <%= @advisor.college_id %>
</p>

<%= link_to 'Edit', edit_advisor_path(@advisor) %> |
<%= link_to 'Back', advisors_path %>