config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  devise_for :advisors, controllers: { omniauth_callbacks: 'advisors/omniauth_callbacks' }, skip: [:sessions]
  as :advisor do
    get 'signin', to: 'devise/sessions#new', as: :new_advisor_session
    post 'signin', to: 'devise/sessions#create', as: :advisor_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_advisor_session
  end
  # authenticated :advisor do
  #   root to: ''
  # end
  resources :courses
  resources :advisors
  resources :students do
    resources :academic_plans
  end

  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/academic_plan.rb
class AcademicPlan < ApplicationRecord
  belongs_to :student
  has_many :course_plans, dependent: :destroy
  has_many :courses, through: :course_plans
  belongs_to :advised_term, class_name: 'AcademicTerm'

  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :advised_term

  def advised_term_attributes=(advised_term_hash)
    advised_term_hash.values.each do |advising_term|
      if advised_term_hash['academic_term_code'].present?
        term = AcademicTerm.find_or_create_by(academic_term_code: advising_term)
          self.advised_term = term
        end
    end
  end

  def courses_attributes=(courses_hash)
    courses_hash.values.each do |course_hash|
      if course_hash['course_code'].present?
        # binding.pry
        get_course = course_hash.values_at('course_code')
        advised_course = Course.find_or_create_by(course_code: get_course)
        # below finds or creates record in course_plans table with courses and academic_plan foreign keys
        academic_plan_course = CoursePlan.find_or_create_by(academic_plan: self, course: advised_course)
        # below creates record in course_plans table with academic_plan foreign key, enables record to be saved
        # without this, the record will lack foreign key academic_plan_id and no courses will appear when
        # courses method called on academic_plan object
        # self.courses << advised_course
      end
    end
  end
end

app/controllers/academic_plans_controller.rb
# frozen_string_literal: true

# controller for AcademicPlans class
class AcademicPlansController < ApplicationController
  before_action :set_student
  before_action :set_academic_plan, only: %i[show edit update destroy]

  # GET /academic_plans or /academic_plans.json
  def index
    @academic_plans = @student.academic_plans
  end

  # GET /academic_plans/1 or /academic_plans/1.json
  def show; end

  # GET /academic_plans/new
  def new
    # binding.pry
    @academic_plan = @student.academic_plans.build
    7.times { @academic_plan.courses.build }
    @academic_plan.build_advised_term
  end

  # GET /academic_plans/1/edit
  def edit
    7.times { @academic_plan.courses.build }
  end

  # POST /academic_plans or /academic_plans.json
  def create
    @academic_plan = @student.academic_plans.create(student_academic_plan_params)
    respond_to do |format|
      if @academic_plan.save
        format.html { redirect_to student_academic_plan_path(@student, @academic_plan), notice: 'Academic plan was successfully created.' }
        format.json { render :show, status: :created, location: @academic_plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @academic_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academic_plans/1 or /academic_plans/1.json
  def update
    # binding.pry
    respond_to do |format|
      if @academic_plan.update(student_academic_plan_params)
        format.html { redirect_to student_academic_plan_path(@student, @academic_plan), notice: 'Academic plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @academic_plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @academic_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academic_plans/1 or /academic_plans/1.json
  def destroy
    @academic_plan.destroy
    respond_to do |format|
      format.html { redirect_to student_academic_plans_path, notice: 'Academic plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_student
    @student = Student.find(params[:student_id])
  end

  def set_academic_plan
    # @student = Student.find(params[:id])
    @academic_plan = @student.academic_plans.find(params[:id])
    # @academic_plan.build_advised_term
  end

  # Only allow a list of trusted parameters through.
  def student_academic_plan_params
    params.require(:academic_plan).permit(:academic_plan_note, :id,
                                          courses_attributes: %i[id course_code _destroy advised_term],
                                          advised_term_attributes: %i[id academic_term_code _destroy])
  end
end

app/helpers/academic_plans_helper.rb
module AcademicPlansHelper

end

app/views/academic_plans/_form.html.erb
<%= bootstrap_form_for([@student, @academic_plan], layout: :floating) do |form| %>
  <% if academic_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(academic_plan.errors.count, "error") %> prohibited this academic_plan from being saved:</h2>

      <ul>
        <% academic_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>~
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-6">
        <%= form.fields_for :courses, { layout: :floating, for: "floatingInput" } do |course_form| %>
          <% course_form.hidden_field :id %>
          <%#= course_form.label :floatingInput %>
          <%= course_form.text_field :course_code, list: "course_code_autocomplete" %>
          <datalist id="course_code_autocomplete">
            <% Course.all.each do |course| %>
              <option value="<%= course.course_code %>"><%= course.course_code %> - <%= course.course_title %></option>
            <% end %>
          </datalist>
      <% end %>
      </div>
      <div class="col-3">
        <div class="field">
          <%= form.text_area :academic_plan_note, class: "form-control" %>
        </div>
      </div>
      <div class="col-3">
        <div class="form-floating">
          <%= form.fields_for :advised_term do |advised| %>
            <%= advised.text_field :academic_term_code, list: "academic_term_autocomplete", class: "form-control" %>
            <datalist id="academic_term_autocomplete">
              <% AcademicTerm.all.each do |term| %>
                <option value="<%= term.academic_term_code %>"><%= term.academic_term %></option>
              <% end %>
            </datalist>
          <% end %>
        </div>
      </div>


<!--  <div class="field">-->
    <%#= form.label :advisor_id %>
    <%#= form.text_field :advisor_id %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

<%= console %>

app/views/academic_plans/edit.html.erb
<h1>Editing Academic Plan</h1>

<%= render 'form', academic_plan: @academic_plan %>

<%= link_to 'Show', student_academic_plan_path(@student, @academic_plan) %> |
<%= link_to 'Back', student_academic_plans_path %>

app/views/academic_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Academic Plans</h1>

<table>
  <thead>
    <tr>
      <th>Academic plan note</th>
      <th>Student</th>
      <th>Advisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student.academic_plans.each do |academic_plan| %>
  <%# raise academic_plan.inspect %>
      <tr>
        <td><%= academic_plan.academic_plan_note %></td>
        <td><%= academic_plan.student_id %></td>
        <td><%= link_to 'Show', student_academic_plan_path(academic_plan.student, academic_plan) %></td>
        <td><%= link_to 'Edit', edit_student_academic_plan_path(academic_plan.student, academic_plan) %></td>
        <td><%= link_to 'Destroy', student_academic_plan_path(academic_plan.student_id, academic_plan), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Academic Plan', new_student_academic_plan_path %> |
<%= link_to 'Back to Student', student_path(@student) %>

app/views/academic_plans/new.html.erb
<h1>New Academic Plan for <%= @student.preferred_name %></h1>

<%= render 'form', academic_plan: @academic_plan %>

<%= link_to 'Back', student_academic_plans_path %>

app/views/academic_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Academic plan note:</strong>
  <%= @academic_plan.academic_plan_note %>
</p>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Course Title</th>
      <th>Credit hours</th>
    </tr>
  </thead>
  <tbody>
  <% @academic_plan.courses.each do |plan_course| %>
    <tr>
      <td><%= plan_course.course_code %></td>
      <td><%= plan_course.course_title %></td>
      <td><%= plan_course.credit_hrs %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <strong>Student:</strong>
  <%= @academic_plan.student_id %>
</p>

<%= link_to 'Edit', edit_student_academic_plan_path(@student, @academic_plan) %> |
<%= link_to 'Back', student_academic_plans_path %>